name    'de-wiring/docker_hardening'
version '0.0.1'
source 'https://github.com/de-wiring/puppet-docker-hardening'
author 'Christian Neudert'
license 'Apache License, Version 2.0'
summary 'Installs and configures Docker with hardening'
description 'Installs and configures Docker with hardening'
project_page 'https://github.com/de-wiring/puppet-docker-hardening'

dependency 'garethr/docker', '>= 4.1.1'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'puppetlabs/apt'
